accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'
urlpatterns =[
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('blogs.urls')),
    
]

blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('overall/', views.overall, name = 'overall'),
    path('overall/<int:overal_id>/', views.overal, name='overal'),
    path('new_overall/', views.new_overall, name='new_overall'),
    path('new_explain/<int:overal_id>/', views.new_explain, name='new_explain'),
    path('edit_overall/<int:overall_id>/', views.edit_overall, name='edit_overall'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Overall(models.Model):
    name = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    

class Individaul(models.Model):
    name = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    
class Explain(models.Model):
    esm = models.ForeignKey(Overall, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a simple string representing the entry."""
        return f"{self.text[:50]}..."
    
class Explain2(models.Model):
    esmm = models.ForeignKey(Individaul, on_delete=models.CASCADE)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name
    

blogs/forms.py
from django import forms

from .models import Overall,Explain

class OverallForm(forms.ModelForm):
    class Meta:
        model = Overall
        fields = ['name']
        labels = {'name': ''}

class ExplainForm(forms.ModelForm):
    class Meta:
        model = Explain
        fields = ['name']
        labels = {'name': ''}
        widgets = {'name': forms.Textarea(attrs={'cols': 80})}

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
# Create your views here.


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('blogs:index')
        
    context = {'form': form}
    return render(request, 'registration/register.html', context)

blogs/views.py
from django.shortcuts import render, redirect
from .models import Overall, Explain, Explain2, Individaul
from .forms import OverallForm, ExplainForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import Http404




# Create your views here.
def index(request):
    return render(request, 'blogs/index.html')

@login_required
def overall(request):
    overall = Overall.objects.filter(owner=request.user).order_by('date_added')
    context = {'overall': overall}
    return render(request, 'blogs/overall.html', context)
    

@login_required
def overal(request, overal_id):
    overal = Overall.objects.get(id=overal_id)
    if overal.owner != request.user:
        raise Http404
    
    explains = overal.explain_set.order_by('-date_added')
    context = {'overal': overal, 'explains': explains}
    return render(request, 'blogs/overal.html', context)


@login_required
def new_overall(request):
    
    if request.method != 'POST':
        form = OverallForm()
    else:
        form = OverallForm(data=request.POST)
        if form.is_valid():
            new_overall = form.save(commit=False)
            new_overall.owner = request.user
            new_overall.save()
            return redirect('blogs:overall')
        
    context = {'form': form}
    return render(request,'blogs/new_overall.html', context)


@login_required
def new_explain(request, overal_id):
    overal = Overall.objects.get(id=overal_id)
    if overal.owner != request.user:
        raise Http404
    
    if request.method != 'POST':
        form = ExplainForm()
    else:
        form = ExplainForm(data=request.POST)
        if form.is_valid():
            new_explain = form.save(commit=False)
            new_explain.owner = request.user
            new_explain.overal = overal
            new_explain.overl_id = overal_id
            new_explain.esm = overal
            new_explain.save()
            return redirect('blogs:overal', overal_id=overal_id)
        
    context = {'overal': overal,'form': form }
    return render(request, 'blogs/new_explain.html', context)


@login_required
def edit_overall(request, overall_id):
    overall = Explain.objects.get(id=overall_id)
    overal = overall.esm
    if overal.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = ExplainForm(instance=overall)
    else:
        form = ExplainForm(instance=overall, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('blogs:overal', overal_id=overal.id)
    
    context = {'overall': overall, 'form': form, 'overal': overal}
    return render(request, 'blogs/edit_overall.html', context)



blogs/templates/blogs/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OpenVibes</title>

    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'blogs:index' %}">OpenVibes</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
            data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:overall' %}">
                        Overall</a></li>
            </ul> <!-- End of account-related links-->

            <ul class="navbar-nav ms-auto mb-2 mb-md-0">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                    <span class="navbar-text me-2">Welcome back, {{ user.username}}.
                      </span></li>
                {% else %} 
      `           <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:register' %}">
                    Register</a></li>
                    <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                    Log in</a></li>
                {% endif %}

        </ul> <!-- End of account-related links-->

                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post">
                    {% csrf_token %}
                    <button name="submit" class="'btn btn-outline-secondary btn-sm">
                    Log out</button>
                    </form>
                {% endif %}

        </div> <!-- Closes collapsible parts of navbar-->
    </div> <!-- Closes navbar's container -->
</nav> <!-- End of navbar -->

<main class="container">
    <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>

blogs/templates/blogs/edit_overall.html
{% extends 'blogs/base.html' %}

{% load django_bootstrap5 %}



{% block page_header %}
  <h2>Edit overall.</h2>
{% endblock page_header %}

{% block content %}
    <p><a href="{% url 'blogs:overal' overal.id %}">{{ overal }}</a></p>

  <form action="{% url 'blogs:edit_overall' overall.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Edit overall" %}
</form>

{% endblock content %}

blogs/templates/blogs/index.html
{% extends 'blogs/base.html' %}

{% block page_header %}
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-4">
            <h1 class="display-3">Be part of a vibrant community where your words find a home.</h1>

            <p class="lead">Open vibes is a warm, inviting weblog where anyone can freely share their thoughts,
              stories, dreams, or random musings. Its simple, intuitive design lets you post effortlessly,
              while a kind, inclusive community cheers you on.
              Create your own space, connect through words,
              and let your voice shine!.</p>
        {% if user.is_authenticated %}
        <li class="nav-item">
        <span class="navbar-text me-2">Hello, {{ user.username }}.
          </span></li>
        {% else %}
            <a class="btn btn-primary btn-lg mt-1"
              href="{% url 'accounts:register' %}">Register &raquo;</a>
        {% endif %}
        </div>
    </div>
{% endblock page_header %}
     

blogs/templates/blogs/new_explain.html
{% extends 'blogs/base.html' %}

{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new explaination.</h2>
{% endblock page_header %}

{% block content %}
    <p><a href="{% url 'blogs:overal' overal.id %}">{{ overal }}</a></p>

    <form action="{% url 'blogs:new_explain' overal.id %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add a explaination" %}
</form>

{% endblock content %}

blogs/templates/blogs/new_overall.html
{% extends 'blogs/base.html' %}
{% load django_bootstrap5 %}

{% block page_header %}
  <h2>Add a new overall.</h2>
{% endblock page_header %}

{% block content %}

  <form action="{% url 'blogs:new_overall' %}" method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button button_type="submit" content="Add a overall" %}
</form>

{% endblock content %}

blogs/templates/blogs/overal.html
{% extends 'blogs/base.html' %}


{% block page_header %}
  <h1>{{ overal.name }}</h1>
{% endblock page_header %}

{% block content %}

<p>Short Explanation:</p>
<p>
  <a href="{% url 'blogs:new_explain' overal.id %}">Add a new explanation</a>
</p>

    {% for explain in explains %}
      <div class="card mb-3">
        <!-- Card header with timestamp and edit link -->
        <h4 class="card-header">
          {{ explain.date_added|date:'M d, Y H:i' }}
          <small><a href="{% url 'blogs:edit_overall' explain.id %}">
            Edit overall</a></small>
        </h4>
        <div class="card-body">{{ explain.name|linebreaks }}</div>
      </div>
    {% empty %}
      <li>No explanation have been added yet.</li>
    {% endfor %}

{% endblock content %}

blogs/templates/blogs/overall.html
{% extends 'blogs/base.html' %}

{% block page_header %}
  <h1>Overall blogs</h1>
{% endblock page_header %}

{% block content %}
<ul class="list-group bprder-bottom pb-2 mb-4">
    {% for overal in overall %}
      <li class="list-group-item border-0">
        <a href="{% url 'blogs:overal' overal.id %}">
        <li class="nav-item">
        <span class="navbar-text me-2">{{ overal }}
          </span></li>
      </li>
    {% empty %}
      <li class="list-group-item border-0">No blogs have been added yet.</li>
    {% endfor %}
</ul>

<a href="{% url 'blogs:new_overall' %}">Add a new overall</a>

{% endblock content %}